language: php

php:
  - 5.4
  - 5.5

env:
  - MONGO_VERSION=1.2.12

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-clover build/clover.xml
  - php build/coverage-checker.php build/clover.xml 84
  - vendor/bin/phpmd --exclude ClassMetadataTrait.php lib/ text ruleset.xml
  - vendor/bin/phpcs --standard=PSR2 lib/ tests/Zoop/
